--- #YAML:1.0
name:               Data-UUID
version:            1.149
abstract:           Perl extension for generating Globally/Universally 
author:
    - Ricardo Signes <rjbs[at]cpan.org>
license:            bsd
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
